### ISSUE TITLE
Somethin on case

### ISSUE THREAD

**Issue by PGA68** [togajs/toga-sample#1]
\home\toga\node_modules\toga-sample\index.js:8
import through from 'through2';
^^^^^^
SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)

**Comment by shannonmoeller** [comment]
Thanks. Toga isn't ready for production use yet. Errors like this are currently to be expected.
